<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Criação de aproximadamente 500 seeders de estados para popular o banco de dados.
     */
    public function run(): void
    {
        City::create(['state_id' => 1, 'name' => 'Acrelândia']);
        City::create(['state_id' => 1, 'name' => 'Assis Brasil']);
        City::create(['state_id' => 1, 'name' => 'Brasiléia']);
        City::create(['state_id' => 1, 'name' => 'Bujari']);
        City::create(['state_id' => 1, 'name' => 'Capixaba']);
        City::create(['state_id' => 1, 'name' => 'Cruzeiro do Sul']);
        City::create(['state_id' => 2, 'name' => 'Olivença']);
        City::create(['state_id' => 2, 'name' => 'Porto Calvo']);
        City::create(['state_id' => 2, 'name' => 'Teotônio Vilela']);
        City::create(['state_id' => 2, 'name' => 'Viçosa']);
        City::create(['state_id' => 3, 'name' => 'Amapá']);
        City::create(['state_id' => 3, 'name' => 'Ambé']);
        City::create(['state_id' => 3, 'name' => 'Calçoene']);
        City::create(['state_id' => 3, 'name' => 'Cutias']);
        City::create(['state_id' => 3, 'name' => 'Ferreira Gomes']);
        City::create(['state_id' => 3, 'name' => 'Itaubal']);
        City::create(['state_id' => 3, 'name' => 'Laranjal do Jari']);
        City::create(['state_id' => 3, 'name' => 'Macapá']);
        City::create(['state_id' => 3, 'name' => 'Mazagão']);
        City::create(['state_id' => 3, 'name' => 'Oiapoque']);
        City::create(['state_id' => 3, 'name' => 'Pedra Branca do Amaparí']);
        City::create(['state_id' => 3, 'name' => 'Porto Grande']);
        City::create(['state_id' => 3, 'name' => 'Pracuúba']);
        City::create(['state_id' => 3, 'name' => 'Santana']);
        City::create(['state_id' => 3, 'name' => 'Serra do Navio']);
        City::create(['state_id' => 3, 'name' => 'Tartarugalzinho']);
        City::create(['state_id' => 3, 'name' => 'Vitória do Jari']);
        City::create(['state_id' => 4, 'name' => 'Alvarães']);
        City::create(['state_id' => 4, 'name' => 'Boa Vista do Ramos']);
        City::create(['state_id' => 4, 'name' => 'Careiro da Várzea']);
        City::create(['state_id' => 4, 'name' => 'Envira']);
        City::create(['state_id' => 4, 'name' => 'Nova Olinda do Norte']);
        City::create(['state_id' => 4, 'name' => 'Novo Airão']);
        City::create(['state_id' => 4, 'name' => 'Novo Aripuanã']);
        City::create(['state_id' => 4, 'name' => 'Rio Preto da Eva']);
        City::create(['state_id' => 4, 'name' => 'São Paulo de Olivença']);
        City::create(['state_id' => 4, 'name' => 'Silves']);
        City::create(['state_id' => 5, 'name' => 'Antônio Gonçalves']);
        City::create(['state_id' => 5, 'name' => 'Barra da Estiva']);
        City::create(['state_id' => 5, 'name' => 'Boa Nova']);
        City::create(['state_id' => 5, 'name' => 'Boa Vista do Tupim']);
        City::create(['state_id' => 5, 'name' => 'Canavieiras']);
        City::create(['state_id' => 5, 'name' => 'Caravelas']);
        City::create(['state_id' => 5, 'name' => 'Cardeal da Silva']);
        City::create(['state_id' => 5, 'name' => 'Casa Nova']);
        City::create(['state_id' => 5, 'name' => 'Castro Alves']);
        City::create(['state_id' => 5, 'name' => 'Cravolândia']);
        City::create(['state_id' => 5, 'name' => 'Dias DÁvila']);
        City::create(['state_id' => 5, 'name' => 'Firmino Alves']);
        City::create(['state_id' => 5, 'name' => 'Gavião']);
        City::create(['state_id' => 5, 'name' => 'Governador Mangabeira']);
        City::create(['state_id' => 5, 'name' => 'Livramento de Nossa Senhora']);
        City::create(['state_id' => 5, 'name' => 'Manoel Vitorino']);
        City::create(['state_id' => 5, 'name' => 'Mundo Novo']);
        City::create(['state_id' => 5, 'name' => 'Nova Canaã']);
        City::create(['state_id' => 5, 'name' => 'Nova Fátima']);
        City::create(['state_id' => 5, 'name' => 'Nova Ibiá']);
        City::create(['state_id' => 5, 'name' => 'Nova Itarana']);
        City::create(['state_id' => 5, 'name' => 'Nova Redenção']);
        City::create(['state_id' => 5, 'name' => 'Nova Soure']);
        City::create(['state_id' => 5, 'name' => 'Nova Viçosa']);
        City::create(['state_id' => 5, 'name' => 'Novo Horizonte']);
        City::create(['state_id' => 5, 'name' => 'Novo Triunfo']);
        City::create(['state_id' => 5, 'name' => 'Oliveira dos Brejinhos']);
        City::create(['state_id' => 5, 'name' => 'Ponto Novo']);
        City::create(['state_id' => 5, 'name' => 'Presidente Tancredo Neves']);
        City::create(['state_id' => 5, 'name' => 'Riachão das Neves']);
        City::create(['state_id' => 5, 'name' => 'Salvador']);
        City::create(['state_id' => 5, 'name' => 'Santa Cruz da Vitória']);
        City::create(['state_id' => 5, 'name' => 'Santa Maria da Vitória']);
        City::create(['state_id' => 5, 'name' => 'Santo Estevão']);
        City::create(['state_id' => 5, 'name' => 'São José da Vitória']);
        City::create(['state_id' => 5, 'name' => 'Tabocas do Brejo Velho']);
        City::create(['state_id' => 5, 'name' => 'Tanque Novo']);
        City::create(['state_id' => 5, 'name' => 'Terra Nova']);
        City::create(['state_id' => 5, 'name' => 'Valença']);
        City::create(['state_id' => 5, 'name' => 'Valente']);
        City::create(['state_id' => 5, 'name' => 'Várzea da Roça']);
        City::create(['state_id' => 5, 'name' => 'Várzea do Poço']);
        City::create(['state_id' => 5, 'name' => 'Várzea Nova']);
        City::create(['state_id' => 5, 'name' => 'Varzedo']);
        City::create(['state_id' => 5, 'name' => 'Vera Cruz']);
        City::create(['state_id' => 5, 'name' => 'Vereda']);
        City::create(['state_id' => 5, 'name' => 'Vitória da Conquista']);
        City::create(['state_id' => 6, 'name' => 'Boa Viagem']);
        City::create(['state_id' => 6, 'name' => 'Cascavel']);
        City::create(['state_id' => 6, 'name' => 'Chaval']);
        City::create(['state_id' => 6, 'name' => 'Lavras da Mangabeira']);
        City::create(['state_id' => 6, 'name' => 'Missão Velha']);
        City::create(['state_id' => 6, 'name' => 'Morada Nova']);
        City::create(['state_id' => 6, 'name' => 'Nova Olinda']);
        City::create(['state_id' => 6, 'name' => 'Nova Russas']);
        City::create(['state_id' => 6, 'name' => 'Novo Oriente']);
        City::create(['state_id' => 6, 'name' => 'Varjota']);
        City::create(['state_id' => 6, 'name' => 'Várzea Alegre']);
        City::create(['state_id' => 6, 'name' => 'Viçosa do Ceará']);
        City::create(['state_id' => 7, 'name' => 'Brasília']);
        City::create(['state_id' => 8, 'name' => 'Alfredo Chaves']);
        City::create(['state_id' => 8, 'name' => 'Alto Rio Novo']);
        City::create(['state_id' => 8, 'name' => 'Atílio Vivácqua']);
        City::create(['state_id' => 8, 'name' => 'Divino de São Lourenço']);
        City::create(['state_id' => 8, 'name' => 'Governador Lindenberg']);
        City::create(['state_id' => 8, 'name' => 'João Neiva']);
        City::create(['state_id' => 8, 'name' => 'Nova Venécia']);
        City::create(['state_id' => 8, 'name' => 'Rio Novo do Sul']);
        City::create(['state_id' => 8, 'name' => 'Vargem Alta']);
        City::create(['state_id' => 8, 'name' => 'Venda Nova do Imigrante']);
        City::create(['state_id' => 8, 'name' => 'Viana']);
        City::create(['state_id' => 8, 'name' => 'Vila Pavão']);
        City::create(['state_id' => 8, 'name' => 'Vila Valério']);
        City::create(['state_id' => 8, 'name' => 'Vila Velha']);
        City::create(['state_id' => 8, 'name' => 'Vitória']);
        City::create(['state_id' => 9, 'name' => 'Alvorada do Norte']);
        City::create(['state_id' => 9, 'name' => 'Avelinópolis']);
        City::create(['state_id' => 9, 'name' => 'Bela Vista de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Caldas Novas']);
        City::create(['state_id' => 9, 'name' => 'Campos Verdes']);
        City::create(['state_id' => 9, 'name' => 'Campos Verdes']);
        City::create(['state_id' => 9, 'name' => 'Carmo do Rio Verde']);
        City::create(['state_id' => 9, 'name' => 'Carmo do Rio Verde']);
        City::create(['state_id' => 9, 'name' => 'Cavalcante']);
        City::create(['state_id' => 9, 'name' => 'Davinópolis']);
        City::create(['state_id' => 9, 'name' => 'Divinópolis de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Doverlândia']);
        City::create(['state_id' => 9, 'name' => 'Fazenda Nova']);
        City::create(['state_id' => 9, 'name' => 'Fazenda Nova']);
        City::create(['state_id' => 9, 'name' => 'Gouvelândia']);
        City::create(['state_id' => 9, 'name' => 'Ivolândia']);
        City::create(['state_id' => 9, 'name' => 'Joviânia']);
        City::create(['state_id' => 9, 'name' => 'Montividiu']);
        City::create(['state_id' => 9, 'name' => 'Montividiu do Norte']);
        City::create(['state_id' => 9, 'name' => 'Montividiu do Norte']);
        City::create(['state_id' => 9, 'name' => 'Mundo Novo']);
        City::create(['state_id' => 9, 'name' => 'Mundo Novo']);
        City::create(['state_id' => 9, 'name' => 'Nova América']);
        City::create(['state_id' => 9, 'name' => 'Nova América']);
        City::create(['state_id' => 9, 'name' => 'Nova Aurora']);
        City::create(['state_id' => 9, 'name' => 'Nova Crixás']);
        City::create(['state_id' => 9, 'name' => 'Nova Glória']);
        City::create(['state_id' => 9, 'name' => 'Nova Glória']);
        City::create(['state_id' => 9, 'name' => 'Nova Iguaçu de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Nova Iguaçu de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Nova Roma']);
        City::create(['state_id' => 9, 'name' => 'Nova Veneza']);
        City::create(['state_id' => 9, 'name' => 'Nova Veneza']);
        City::create(['state_id' => 9, 'name' => 'Novo Brasil']);
        City::create(['state_id' => 9, 'name' => 'Novo Gama']);
        City::create(['state_id' => 9, 'name' => 'Novo Planalto']);
        City::create(['state_id' => 9, 'name' => 'Novo Planalto']);
        City::create(['state_id' => 9, 'name' => 'Ouro Verde de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Ouro Verde de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Ouvidor']);
        City::create(['state_id' => 9, 'name' => 'Rio Verde']);
        City::create(['state_id' => 9, 'name' => 'Rio Verde']);
        City::create(['state_id' => 9, 'name' => 'Santa Rita do Novo Destino']);
        City::create(['state_id' => 9, 'name' => 'Silvânia']);
        City::create(['state_id' => 9, 'name' => 'Silvânia']);
        City::create(['state_id' => 9, 'name' => 'Turvânia']);
        City::create(['state_id' => 9, 'name' => 'Turvelândia']);
        City::create(['state_id' => 9, 'name' => 'Valparaíso de Goiás']);
        City::create(['state_id' => 9, 'name' => 'Varjão']);
        City::create(['state_id' => 9, 'name' => 'Varjão']);
        City::create(['state_id' => 9, 'name' => 'Vianópolis']);
        City::create(['state_id' => 9, 'name' => 'Vicentinópolis']);
        City::create(['state_id' => 9, 'name' => 'Vila Boa']);
        City::create(['state_id' => 9, 'name' => 'Vila Propício']);
        City::create(['state_id' => 10, 'name' => 'Bela Vista do Maranhão']);
        City::create(['state_id' => 10, 'name' => 'Boa Vista do Gurupi']);
        City::create(['state_id' => 10, 'name' => 'Bom Jesus das Selvas']);
        City::create(['state_id' => 10, 'name' => 'Buriti Bravo']);
        City::create(['state_id' => 10, 'name' => 'Centro Novo do Maranhão']);
        City::create(['state_id' => 10, 'name' => 'Davinópolis']);
        City::create(['state_id' => 10, 'name' => 'Feira Nova do Maranhão']);
        City::create(['state_id' => 10, 'name' => 'Godofredo Viana']);
        City::create(['state_id' => 10, 'name' => 'Gonçalves Dias']);
        City::create(['state_id' => 10, 'name' => 'Governador Archer']);
        City::create(['state_id' => 10, 'name' => 'Governador Edison Lobão']);
        City::create(['state_id' => 10, 'name' => 'Governador Eugênio Barros']);
        City::create(['state_id' => 10, 'name' => 'Governador Luiz Rocha']);
        City::create(['state_id' => 10, 'name' => 'Governador Newton Bello']);
        City::create(['state_id' => 10, 'name' => 'Governador Nunes Freire']);
        City::create(['state_id' => 10, 'name' => 'Itaipava do Grajaú']);
        City::create(['state_id' => 10, 'name' => 'Jenipapo dos Vieiras']);
        City::create(['state_id' => 10, 'name' => 'Lago Verde']);
        City::create(['state_id' => 10, 'name' => 'Lajeado Novo']);
        City::create(['state_id' => 10, 'name' => 'Nova Colinas']);
        City::create(['state_id' => 10, 'name' => 'Nova Iorque']);
        City::create(['state_id' => 10, 'name' => 'Nova Olinda do Maranhão']);
        City::create(['state_id' => 10, 'name' => 'Olinda Nova do Maranhão']);
        City::create(['state_id' => 10, 'name' => 'Paulino Neves']);
        City::create(['state_id' => 10, 'name' => 'Penalva']);
        City::create(['state_id' => 10, 'name' => 'Presidente Vargas']);
        City::create(['state_id' => 10, 'name' => 'São Vicente Ferrer']);
        City::create(['state_id' => 10, 'name' => 'Sítio Novo']);
        City::create(['state_id' => 10, 'name' => 'Trizidela do Vale']);
        City::create(['state_id' => 10, 'name' => 'Vargem Grande']);
        City::create(['state_id' => 10, 'name' => 'Viana']);
        City::create(['state_id' => 10, 'name' => 'Vila Nova dos Martírios']);
        City::create(['state_id' => 10, 'name' => 'Vitória do Mearim']);
        City::create(['state_id' => 10, 'name' => 'Vitorino Freire']);
        City::create(['state_id' => 11, 'name' => 'Novo São Joaquim']);
        City::create(['state_id' => 11, 'name' => 'Peixoto de Azevedo']);
        City::create(['state_id' => 11, 'name' => 'Primavera do Leste']);
        City::create(['state_id' => 11, 'name' => 'Reserva do Cabaçal']);
        City::create(['state_id' => 11, 'name' => 'Santa Rita do Trivelato']);
        City::create(['state_id' => 11, 'name' => 'Santo Antônio do Leverger']);
        City::create(['state_id' => 11, 'name' => 'São José do Povo']);
        City::create(['state_id' => 11, 'name' => 'Serra Nova Dourada']);
        City::create(['state_id' => 11, 'name' => 'Terra Nova do Norte']);
        City::create(['state_id' => 11, 'name' => 'Vale de São Domingos']);
        City::create(['state_id' => 11, 'name' => 'Várzea Grande']);
        City::create(['state_id' => 11, 'name' => 'Vera']);
        City::create(['state_id' => 11, 'name' => 'Vila Bela da Santíssima Trindade']);
        City::create(['state_id' => 11, 'name' => 'Vila Rica']);
        City::create(['state_id' => 12, 'name' => 'Bela Vista']);
        City::create(['state_id' => 12, 'name' => 'Ivinhema']);
        City::create(['state_id' => 12, 'name' => 'Mundo Novo']);
        City::create(['state_id' => 12, 'name' => 'Naviraí']);
        City::create(['state_id' => 12, 'name' => 'Nova Alvorada do Sul']);
        City::create(['state_id' => 12, 'name' => 'Nova Andradina']);
        City::create(['state_id' => 12, 'name' => 'Novo Horizonte do Sul']);
        City::create(['state_id' => 12, 'name' => 'Rio Verde de Mato Grosso']);
        City::create(['state_id' => 12, 'name' => 'Selvíria']);
        City::create(['state_id' => 12, 'name' => 'Vicentina']);
        City::create(['state_id' => 13, 'name' => 'Veredinha']);
        City::create(['state_id' => 13, 'name' => 'Veríssimo']);
        City::create(['state_id' => 13, 'name' => 'Vermelho']);
        City::create(['state_id' => 13, 'name' => 'Vermelho Novo']);
        City::create(['state_id' => 13, 'name' => 'Vespasiano']);
        City::create(['state_id' => 13, 'name' => 'Viçosa']);
        City::create(['state_id' => 13, 'name' => 'Vieiras']);
        City::create(['state_id' => 13, 'name' => 'Virgem da Lapa']);
        City::create(['state_id' => 13, 'name' => 'Virgínia']);
        City::create(['state_id' => 13, 'name' => 'Virginópolis']);
        City::create(['state_id' => 13, 'name' => 'Virgolândia']);
        City::create(['state_id' => 13, 'name' => 'Visconde do Rio Branco']);
        City::create(['state_id' => 13, 'name' => 'Volta Grande']);
        City::create(['state_id' => 14, 'name' => 'Aveiro']);
        City::create(['state_id' => 14, 'name' => 'Benevides']);
        City::create(['state_id' => 14, 'name' => 'Brasil Novo']);
        City::create(['state_id' => 14, 'name' => 'Breves']);
        City::create(['state_id' => 14, 'name' => 'Chaves']);
        City::create(['state_id' => 14, 'name' => 'Mirasselvas']);
        City::create(['state_id' => 14, 'name' => 'Nova Esperança do Piriá']);
        City::create(['state_id' => 14, 'name' => 'Nova Ipixuna']);
        City::create(['state_id' => 14, 'name' => 'Nova Timboteua']);
        City::create(['state_id' => 14, 'name' => 'Novo Progresso']);
        City::create(['state_id' => 14, 'name' => 'Novo Repartimento']);
        City::create(['state_id' => 14, 'name' => 'Primavera']);
        City::create(['state_id' => 14, 'name' => 'Salvaterra']);
        City::create(['state_id' => 14, 'name' => 'Santarém Novo']);
        City::create(['state_id' => 14, 'name' => 'São Caetano de Odivelas']);
        City::create(['state_id' => 14, 'name' => 'São Sebastião da Boa Vista']);
        City::create(['state_id' => 14, 'name' => 'Vigia']);
        City::create(['state_id' => 14, 'name' => 'Viseu']);
        City::create(['state_id' => 14, 'name' => 'Vitória do Xingu']);
        City::create(['state_id' => 15, 'name' => 'Alagoa Nova']);
        City::create(['state_id' => 15, 'name' => 'Boa Ventura']);
        City::create(['state_id' => 15, 'name' => 'Boa Vista']);
        City::create(['state_id' => 15, 'name' => 'Curral Velho']);
        City::create(['state_id' => 15, 'name' => 'Gado Bravo']);
        City::create(['state_id' => 15, 'name' => 'Juarez Távora']);
        City::create(['state_id' => 15, 'name' => 'Livramento']);
        City::create(['state_id' => 16, 'name' => 'Novo Itacolomi']);
        City::create(['state_id' => 16, 'name' => 'Novo Sarandi']);
        City::create(['state_id' => 16, 'name' => 'Ouro Verde do Oeste']);
        City::create(['state_id' => 16, 'name' => 'Paranavaí']);
        City::create(['state_id' => 16, 'name' => 'Porto Vitória']);
        City::create(['state_id' => 16, 'name' => 'Reserva']);
        City::create(['state_id' => 16, 'name' => 'Reserva do Iguaçu']);
        City::create(['state_id' => 16, 'name' => 'Rio Branco do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'Rosário do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'Santa Cecília do Pavão']);
        City::create(['state_id' => 16, 'name' => 'Santa Isabel do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'São Carlos do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'São João do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'São Jorge do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'São José da Boa Vista']);
        City::create(['state_id' => 16, 'name' => 'São Pedro do Ivaí']);
        City::create(['state_id' => 16, 'name' => 'Sede Alvorada']);
        City::create(['state_id' => 16, 'name' => 'Turvo']);
        City::create(['state_id' => 16, 'name' => 'União da Vitória']);
        City::create(['state_id' => 16, 'name' => 'Ventania']);
        City::create(['state_id' => 16, 'name' => 'Vera Cruz do Oeste']);
        City::create(['state_id' => 16, 'name' => 'Verê']);
        City::create(['state_id' => 16, 'name' => 'Vila Nova']);
        City::create(['state_id' => 16, 'name' => 'Virmond']);
        City::create(['state_id' => 16, 'name' => 'Vitorino']);
        City::create(['state_id' => 17, 'name' => 'Arcoverde']);
        City::create(['state_id' => 17, 'name' => 'Arcoverde']);
        City::create(['state_id' => 17, 'name' => 'Arcoverde']);
        City::create(['state_id' => 17, 'name' => 'Arcoverde']);
        City::create(['state_id' => 17, 'name' => 'Feira Nova']);
        City::create(['state_id' => 17, 'name' => 'Gravatá']);
        City::create(['state_id' => 17, 'name' => 'Primavera']);
        City::create(['state_id' => 17, 'name' => 'Santa Cruz da Baixa Verde']);
        City::create(['state_id' => 17, 'name' => 'Santa Maria da Boa Vista']);
        City::create(['state_id' => 17, 'name' => 'São Vicente Ferrer']);
        City::create(['state_id' => 17, 'name' => 'Terra Nova']);
        City::create(['state_id' => 17, 'name' => 'Venturosa']);
        City::create(['state_id' => 17, 'name' => 'Verdejante']);
        City::create(['state_id' => 17, 'name' => 'Vertente do Lério']);
        City::create(['state_id' => 17, 'name' => 'Vertentes']);
        City::create(['state_id' => 17, 'name' => 'Vicência']);
        City::create(['state_id' => 17, 'name' => 'Vitória de Santo Antão']);
        City::create(['state_id' => 18, 'name' => 'Alvorada do Gurguéia']);
        City::create(['state_id' => 18, 'name' => 'Avelino Lopes']);
        City::create(['state_id' => 18, 'name' => 'Bela Vista do Piauí']);
        City::create(['state_id' => 18, 'name' => 'Canavieira']);
        City::create(['state_id' => 18, 'name' => 'Capitão Gervásio Oliveira']);
        City::create(['state_id' => 18, 'name' => 'Cocal dos Alves']);
        City::create(['state_id' => 18, 'name' => 'Coivaras']);
        City::create(['state_id' => 18, 'name' => 'Curral Novo do Piauí']);
        City::create(['state_id' => 18, 'name' => 'Demerval Lobão']);
        City::create(['state_id' => 18, 'name' => 'Dirceu Arcoverde']);
        City::create(['state_id' => 18, 'name' => 'Elesbão Veloso']);
        City::create(['state_id' => 18, 'name' => 'Miguel Alves']);
        City::create(['state_id' => 18, 'name' => 'Nova Santa Rita']);
        City::create(['state_id' => 18, 'name' => 'Novo Oriente do Piauí']);
        City::create(['state_id' => 18, 'name' => 'Novo Santo Antônio']);
        City::create(['state_id' => 18, 'name' => 'Pavussu']);
        City::create(['state_id' => 18, 'name' => 'Queimada Nova']);
        City::create(['state_id' => 18, 'name' => 'Ribeiro Gonçalves']);
        City::create(['state_id' => 18, 'name' => 'São João da Canabrava']);
        City::create(['state_id' => 18, 'name' => 'São João da Varjota']);
        City::create(['state_id' => 18, 'name' => 'São José do Divino']);
        City::create(['state_id' => 18, 'name' => 'Valença do Piauí']);
        City::create(['state_id' => 18, 'name' => 'Várzea Branca']);
        City::create(['state_id' => 18, 'name' => 'Várzea Grande']);
        City::create(['state_id' => 18, 'name' => 'Vera Mendes']);
        City::create(['state_id' => 18, 'name' => 'Vila Nova do Piauí']);
        City::create(['state_id' => 19, 'name' => 'Comendador Levy Gasparian']);
        City::create(['state_id' => 19, 'name' => 'Italva']);
        City::create(['state_id' => 19, 'name' => 'Natividade']);
        City::create(['state_id' => 19, 'name' => 'Nova Friburgo']);
        City::create(['state_id' => 19, 'name' => 'Nova Iguaçu']);
        City::create(['state_id' => 19, 'name' => 'São José do Vale do Rio Preto']);
        City::create(['state_id' => 19, 'name' => 'Silva Jardim']);
        City::create(['state_id' => 19, 'name' => 'Valença']);
        City::create(['state_id' => 19, 'name' => 'Varre-Sai']);
        City::create(['state_id' => 19, 'name' => 'Vassouras']);
        City::create(['state_id' => 19, 'name' => 'Volta Redonda']);
        City::create(['state_id' => 20, 'name' => 'Água Nova']);
        City::create(['state_id' => 20, 'name' => 'Caiçara do Rio do Vento']);
        City::create(['state_id' => 20, 'name' => 'Currais Novos']);
        City::create(['state_id' => 20, 'name' => 'Doutor Severiano']);
        City::create(['state_id' => 20, 'name' => 'Governador Dix-Sept Rosado']);
        City::create(['state_id' => 20, 'name' => 'Lagoa de Velhos']);
        City::create(['state_id' => 20, 'name' => 'Lagoa Nova']);
        City::create(['state_id' => 20, 'name' => 'Marcelino Vieira']);
        City::create(['state_id' => 20, 'name' => 'Nova Cruz']);
        City::create(['state_id' => 20, 'name' => 'Pedro Avelino']);
        City::create(['state_id' => 20, 'name' => 'Pedro Velho']);
        City::create(['state_id' => 20, 'name' => 'São Vicente']);
        City::create(['state_id' => 20, 'name' => 'Senador Georgino Avelino']);
        City::create(['state_id' => 20, 'name' => 'Severiano Melo']);
        City::create(['state_id' => 20, 'name' => 'Sítio Novo']);
        City::create(['state_id' => 20, 'name' => 'Várzea']);
        City::create(['state_id' => 20, 'name' => 'Venha-Ver']);
        City::create(['state_id' => 20, 'name' => 'Vera Cruz']);
        City::create(['state_id' => 21, 'name' => 'Getúlio Vargas']);
        City::create(['state_id' => 21, 'name' => 'Gramado Xavier']);
        City::create(['state_id' => 21, 'name' => 'Gravataí']);
        City::create(['state_id' => 21, 'name' => 'Herval']);
        City::create(['state_id' => 21, 'name' => 'Nova Candelária']);
        City::create(['state_id' => 21, 'name' => 'Santana do Livramento']);
        City::create(['state_id' => 21, 'name' => 'São José do Herval']);
        City::create(['state_id' => 21, 'name' => 'São Valentim']);
        City::create(['state_id' => 21, 'name' => 'Vicente Dutra']);
        City::create(['state_id' => 21, 'name' => 'Victor Graeff']);
        City::create(['state_id' => 21, 'name' => 'Vila Flores']);
        City::create(['state_id' => 21, 'name' => 'Vila Lângaro']);
        City::create(['state_id' => 21, 'name' => 'Vila Maria']);
        City::create(['state_id' => 21, 'name' => 'Vila Nova do Sul']);
        City::create(['state_id' => 21, 'name' => 'Vista Alegre']);
        City::create(['state_id' => 21, 'name' => 'Vista Alegre do Prata']);
        City::create(['state_id' => 21, 'name' => 'Vista Gaúcha']);
        City::create(['state_id' => 21, 'name' => 'Vitória das Missões']);
        City::create(['state_id' => 22, 'name' => 'Alvorada DOeste']);
        City::create(['state_id' => 22, 'name' => 'Campo Novo de Rondônia']);
        City::create(['state_id' => 22, 'name' => 'Governador Jorge Teixeira']);
        City::create(['state_id' => 22, 'name' => 'Nova Brasilândia DOeste']);
        City::create(['state_id' => 22, 'name' => 'Nova Mamoré']);
        City::create(['state_id' => 22, 'name' => 'Nova União']);
        City::create(['state_id' => 22, 'name' => 'Novo Horizonte do Oeste']);
        City::create(['state_id' => 22, 'name' => 'Porto Velho']);
        City::create(['state_id' => 22, 'name' => 'Primavera de Rondônia']);
        City::create(['state_id' => 22, 'name' => 'Vale do Anari']);
        City::create(['state_id' => 22, 'name' => 'Vale do Paraíso']);
        City::create(['state_id' => 22, 'name' => 'Vilhena']);
        City::create(['state_id' => 23, 'name' => 'Boa Vista']);
        City::create(['state_id' => 23, 'name' => 'Bonfim']);
        City::create(['state_id' => 23, 'name' => 'Cantá']);
        City::create(['state_id' => 23, 'name' => 'Caracaraí']);
        City::create(['state_id' => 23, 'name' => 'Caroebe']);
        City::create(['state_id' => 23, 'name' => 'Iracema']);
        City::create(['state_id' => 23, 'name' => 'Mucajaí']);
        City::create(['state_id' => 23, 'name' => 'Normandia']);
        City::create(['state_id' => 23, 'name' => 'Pacaraima']);
        City::create(['state_id' => 23, 'name' => 'Rorainópolis']);
        City::create(['state_id' => 23, 'name' => 'São João da Baliza']);
        City::create(['state_id' => 23, 'name' => 'São Luiz']);
        City::create(['state_id' => 23, 'name' => 'Uiramutã']);
        City::create(['state_id' => 24, 'name' => 'Alto Bela Vista']);
        City::create(['state_id' => 24, 'name' => 'Arvoredo']);
        City::create(['state_id' => 24, 'name' => 'Balneário Arroio do Silva']);
        City::create(['state_id' => 24, 'name' => 'Balneário Gaivota']);
        City::create(['state_id' => 24, 'name' => 'Barra Velha']);
        City::create(['state_id' => 24, 'name' => 'Bela Vista do Toldo']);
        City::create(['state_id' => 24, 'name' => 'Benedito Novo']);
        City::create(['state_id' => 24, 'name' => 'Botuverá']);
        City::create(['state_id' => 24, 'name' => 'Campos Novos']);
        City::create(['state_id' => 24, 'name' => 'Capivari de Baixo']);
        City::create(['state_id' => 24, 'name' => 'Nova Veneza']);
        City::create(['state_id' => 24, 'name' => 'Novo Horizonte']);
        City::create(['state_id' => 24, 'name' => 'Ouro Verde']);
        City::create(['state_id' => 24, 'name' => 'Papanduva']);
        City::create(['state_id' => 24, 'name' => 'Pescaria Brava']);
        City::create(['state_id' => 24, 'name' => 'Salto Veloso']);
        City::create(['state_id' => 24, 'name' => 'São Cristóvão do Sul']);
        City::create(['state_id' => 24, 'name' => 'São Miguel da Boa Vista']);
        City::create(['state_id' => 24, 'name' => 'Treviso']);
        City::create(['state_id' => 24, 'name' => 'Turvo']);
        City::create(['state_id' => 24, 'name' => 'Vargeão']);
        City::create(['state_id' => 24, 'name' => 'Vargem']);
        City::create(['state_id' => 24, 'name' => 'Vargem Bonita']);
        City::create(['state_id' => 24, 'name' => 'Vidal Ramos']);
        City::create(['state_id' => 24, 'name' => 'Videira']);
        City::create(['state_id' => 24, 'name' => 'Vitor Meireles']);
        City::create(['state_id' => 24, 'name' => 'Xavantina']);
        City::create(['state_id' => 25, 'name' => 'Álvares Florence']);
        City::create(['state_id' => 25, 'name' => 'Álvares Machado']);
        City::create(['state_id' => 25, 'name' => 'Álvaro de Carvalho']);
        City::create(['state_id' => 25, 'name' => 'Alvinlândia']);
        City::create(['state_id' => 25, 'name' => 'Arealva']);
        City::create(['state_id' => 25, 'name' => 'Avaí']);
        City::create(['state_id' => 25, 'name' => 'Avanhandava']);
        City::create(['state_id' => 25, 'name' => 'Avaré']);
        City::create(['state_id' => 25, 'name' => 'Barra do Turvo']);
        City::create(['state_id' => 25, 'name' => 'Boituva']);
        City::create(['state_id' => 25, 'name' => 'Cabreúva']);
        City::create(['state_id' => 25, 'name' => 'Caçapava']);
        City::create(['state_id' => 25, 'name' => 'Campos Novos Paulista']);
        City::create(['state_id' => 25, 'name' => 'Capivari']);
        City::create(['state_id' => 25, 'name' => 'Catanduva']);
        City::create(['state_id' => 25, 'name' => 'Chavantes']);
        City::create(['state_id' => 25, 'name' => 'Cravinhos']);
        City::create(['state_id' => 25, 'name' => 'Descalvado']);
        City::create(['state_id' => 25, 'name' => 'Divinolândia']);
        City::create(['state_id' => 25, 'name' => 'Espírito Santo do Turvo']);
        City::create(['state_id' => 25, 'name' => 'Estiva Gerbi']);
        City::create(['state_id' => 25, 'name' => 'Ferraz de Vasconcelos']);
        City::create(['state_id' => 25, 'name' => 'Gastão Vidigal']);
        City::create(['state_id' => 25, 'name' => 'Gavião Peixoto']);
        City::create(['state_id' => 25, 'name' => 'Igarapava']);
        City::create(['state_id' => 25, 'name' => 'Nova Europa']);
        City::create(['state_id' => 25, 'name' => 'Nova Granada']);
        City::create(['state_id' => 25, 'name' => 'Nova Guataporanga']);
        City::create(['state_id' => 25, 'name' => 'Nova Independência']);
        City::create(['state_id' => 25, 'name' => 'Nova Luzitânia']);
        City::create(['state_id' => 25, 'name' => 'Nova Odessa']);
        City::create(['state_id' => 25, 'name' => 'Novais']);
        City::create(['state_id' => 25, 'name' => 'Novo Horizonte']);
        City::create(['state_id' => 25, 'name' => 'Onda Verde']);
        City::create(['state_id' => 25, 'name' => 'Orindiúva']);
        City::create(['state_id' => 25, 'name' => 'Osvaldo Cruz']);
        City::create(['state_id' => 25, 'name' => 'Ouro Verde']);
        City::create(['state_id' => 25, 'name' => 'Presidente Alves']);
        City::create(['state_id' => 25, 'name' => 'Valparaíso']);
        City::create(['state_id' => 25, 'name' => 'Vargem']);
        City::create(['state_id' => 25, 'name' => 'Vargem Grande do Sul']);
        City::create(['state_id' => 25, 'name' => 'Vargem Grande Paulista']);
        City::create(['state_id' => 25, 'name' => 'Várzea Paulista']);
        City::create(['state_id' => 25, 'name' => 'Vera Cruz']);
        City::create(['state_id' => 25, 'name' => 'Vinhedo']);
        City::create(['state_id' => 25, 'name' => 'Viradouro']);
        City::create(['state_id' => 25, 'name' => 'Vista Alegre do Alto']);
        City::create(['state_id' => 25, 'name' => 'Vitória Brasil']);
        City::create(['state_id' => 25, 'name' => 'Votorantim']);
        City::create(['state_id' => 25, 'name' => 'Votuporanga']);
        City::create(['state_id' => 26, 'name' => 'Altos Verdes']);
        City::create(['state_id' => 26, 'name' => 'Divina Pastora']);
        City::create(['state_id' => 26, 'name' => 'Feira Nova']);
        City::create(['state_id' => 26, 'name' => 'Poço Verde']);
        City::create(['state_id' => 26, 'name' => 'São Cristóvão']);
        City::create(['state_id' => 27, 'name' => 'Alvorada']);
        City::create(['state_id' => 27, 'name' => 'Chapada da Natividade']);
        City::create(['state_id' => 27, 'name' => 'Divinópolis do Tocantins']);
        City::create(['state_id' => 27, 'name' => 'Lavandeira']);
        City::create(['state_id' => 27, 'name' => 'Natividade']);
        City::create(['state_id' => 27, 'name' => 'Nova Olinda']);
        City::create(['state_id' => 27, 'name' => 'Nova Rosalândia']);
        City::create(['state_id' => 27, 'name' => 'Novo Acordo']);
        City::create(['state_id' => 27, 'name' => 'Novo Alegre']);
        City::create(['state_id' => 27, 'name' => 'Novo Jardim']);
        City::create(['state_id' => 27, 'name' => 'Oliveira de Fátima']);
        City::create(['state_id' => 27, 'name' => 'São Salvador do Tocantins']);
        City::create(['state_id' => 27, 'name' => 'São Valério da Natividade']);
        City::create(['state_id' => 27, 'name' => 'Silvanópolis']);
        City::create(['state_id' => 27, 'name' => 'Sítio Novo do Tocantins']);
    }
}
