<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Street;

class StreetSeeder extends Seeder
{
    /**
     * Criação de aproximadamente 500 seeders de ruas com bairros para popular o banco de dados.
     */
    public function run(): void
    {
        Street::create(['city_id' => 1, 'name' => 'Avenida Paraná - Centro']);
        Street::create(['city_id' => 343, 'name' => 'Rua Nossa Senhora de Fátima  - Centro']);
        Street::create(['city_id' => 98, 'name' => 'Avenida Getúlio Vargas  - Centro']);
        Street::create(['city_id' => 404, 'name' => 'Rua do Comércio - Centro']);
        Street::create(['city_id' => 99, 'name' => 'Avenida João Felipe  - Centro']);
        Street::create(['city_id' => 28, 'name' => 'Avenida Sete de Setembro - Centro']);
        Street::create(['city_id' => 431, 'name' => 'Rua Rio Grande do Sul - Centro']);
        Street::create(['city_id' => 432, 'name' => 'Rua Pedro Mazzaro - Centro']);
        Street::create(['city_id' => 433, 'name' => 'Praça Otacílio Pereira Nobre - Centro']);
        Street::create(['city_id' => 434, 'name' => 'Avenida Doutor Couto Junior - Centro']);
        Street::create(['city_id' => 486, 'name' => 'Rua José Lins do Rego - Maria Regina']);
        Street::create(['city_id' => 486, 'name' => 'Avenida Contorno - Setor Central']);
        Street::create(['city_id' => 306, 'name' => 'Rua Joaquim Bernardo de Aguiar - Centro']);
        Street::create(['city_id' => 379, 'name' => 'Rua Guimaraes Rosa - Centro']);
        Street::create(['city_id' => 11, 'name' => 'Avenida Guarani - Centro']);
        Street::create(['city_id' => 38, 'name' => 'Praça Presidente Kennedy - Centro']);
        Street::create(['city_id' => 292, 'name' => 'Avenida Um - Santos Dumont']);
        Street::create(['city_id' => 435, 'name' => 'Rua Arthur Robton - Centro']);
        Street::create(['city_id' => 405, 'name' => 'Rua Rio Branco - Centro']);
        Street::create(['city_id' => 2, 'name' => 'Rua Dom Giocondo Maria Grotte - Centro']);
        Street::create(['city_id' => 100, 'name' => 'Rua Primo Luiz Baptista - Niterói']);
        Street::create(['city_id' => 436, 'name' => 'Rua Osório Machado  - Centro']);
        Street::create(['city_id' => 437, 'name' => 'Rua do Café  - Centro']);
        Street::create(['city_id' => 438, 'name' => 'Rua Santa Catarina - Centro']);
        Street::create(['city_id' => 238, 'name' => 'Avenida Humberto de Abreu Frazão  - Centro']);
        Street::create(['city_id' => 114, 'name' => 'Avenida Anicuns - Setor Irani']);
        Street::create(['city_id' => 406, 'name' => 'Avenida Barriga Verde 627 Loja - Centro']);
        Street::create(['city_id' => 407, 'name' => 'Rua Xavantes - Centro']);
        Street::create(['city_id' => 39, 'name' => 'Praça Ruy Barbosa - Centro']);
        Street::create(['city_id' => 439, 'name' => 'Avenida Vinte e Um de Março - Centro']);
        Street::create(['city_id' => 408, 'name' => 'Rua Paraná - Centro']);
        Street::create(['city_id' => 215, 'name' => 'Rua Antônio Maria Coelho  - Centro']);
        Street::create(['city_id' => 115, 'name' => 'Rua Professor Aristoclides Teixeira 6 Quadra 51 - Jardim Barcelona']);
        Street::create(['city_id' => 167, 'name' => 'Rua do Comércio 119 Lote A - Centro']);
        Street::create(['city_id' => 308, 'name' => 'Rua Tiago Marques Barbosa 384 Quadra 24 Lote 384 - Centro']);
        Street::create(['city_id' => 410, 'name' => 'Rua Quirino Longo - Centro']);
        Street::create(['city_id' => 239, 'name' => 'Rua Paulo Begot - Centro']);
        Street::create(['city_id' => 40, 'name' => 'Praça Sete de Setembro - Centro']);
        Street::create(['city_id' => 85, 'name' => 'Praça Monsenhor José Cândido - Centro']);
        Street::create(['city_id' => 391, 'name' => 'Rua Prefeito Severino Bezerra Cabral - Centro']);
        Street::create(['city_id' => 391, 'name' => 'Avenida Ville Roy - Centro']);
        Street::create(['city_id' => 168, 'name' => 'Rua da Matriz - Centro']);
        Street::create(['city_id' => 29, 'name' => 'Rua Emanuel Mafra - Centro']);
        Street::create(['city_id' => 41, 'name' => 'Praça Ruy Barbosa - Centro']);
        Street::create(['city_id' => 440, 'name' => 'Rodovia José Sartorelli 2105 Quilômetro 2 - Santo Antonio']);
        Street::create(['city_id' => 169, 'name' => 'Rua dos Jambeiros - Centro']);
        Street::create(['city_id' => 392, 'name' => 'Rua Olívio Villefort  - Centro']);
        Street::create(['city_id' => 392, 'name' => 'Rua da Damásio Vicente Silva  - Centro']);
        Street::create(['city_id' => 411, 'name' => 'Rua Vereador Pedro Merizio - Centro']);
        Street::create(['city_id' => 240, 'name' => 'Avenida Castelo Branco - Centro']);
        Street::create(['city_id' => 3, 'name' => 'Avenida Prefeito Rolando Moreira - Centro']);
        Street::create(['city_id' => 97, 'name' => 'SBN Quadra 1 Bloco A - Asa Norte']);
        Street::create(['city_id' => 241, 'name' => 'Praça Capitão Dário Furtado - Centro']);
        Street::create(['city_id' => 4, 'name' => 'Rua Expedito Pereira de Souza - Centro']);
        Street::create(['city_id' => 170, 'name' => 'Rua da Bandeira - Centro']);
        Street::create(['city_id' => 441, 'name' => 'Rua Cônego Motta  - Centro']);
        Street::create(['city_id' => 442, 'name' => 'Rua Engenheiro Carlos Roberto Carboenin - Vila Pantaleão']);
        Street::create(['city_id' => 116, 'name' => 'Rua Capitão João Crisóstomo - Setor Central']);
        Street::create(['city_id' => 380, 'name' => 'Avenida Tancredo Neves - Centro']);
        Street::create(['city_id' => 412, 'name' => 'Rua Marechal Floriano Peixoto - Centro']);
        Street::create(['city_id' => 443, 'name' => 'Rua Marechal Deodoro - Centro']);
        Street::create(['city_id' => 118, 'name' => 'Avenida Campos Verdes - Setor Central']);
        Street::create(['city_id' => 42, 'name' => 'Praça Quinze de Novembro - Centro']);
        Street::create(['city_id' => 444, 'name' => 'Rua Barão do Rio Branco - Centro']);
        Street::create(['city_id' => 413, 'name' => 'Rua Machado de Assis 542 Loja - Centro']);
        Street::create(['city_id' => 5, 'name' => 'Rua Ocimar Tessinari - Conquista']);
        Street::create(['city_id' => 394, 'name' => 'Avenida Doutor Zanny - Centro']);
        Street::create(['city_id' => 120, 'name' => 'Avenida Anestar Clemente da Silva - Setor Central']);
        Street::create(['city_id' => 395, 'name' => 'Rodovia BR-210 km 01 - Centro']);
        Street::create(['city_id' => 45, 'name' => 'Rodovia BR 235 - Ouricuri']);
        Street::create(['city_id' => 86, 'name' => 'Praça Horácio Bessa - Centro']);
        Street::create(['city_id' => 86, 'name' => 'Avenida Brasil - Centro']);
        Street::create(['city_id' => 46, 'name' => 'Praça da Liberdade - Riacho da Légua']);
        Street::create(['city_id' => 445, 'name' => 'Rua Ceará - Centro']);
        Street::create(['city_id' => 171, 'name' => 'Rua do Comércio - Centro']);
        Street::create(['city_id' => 87, 'name' => 'Rua Eduardo Mota - Centro']);
        Street::create(['city_id' => 446, 'name' => 'Rua Altino Arantes - Centro']);
        Street::create(['city_id' => 332, 'name' => 'Rua Doutora Josefina Gasparian 61 Loja - Centro']);
        Street::create(['city_id' => 447, 'name' => 'Rua XV de Novembro - Centro']);
        Street::create(['city_id' => 6, 'name' => 'Rua Rego Barros - Centro']);
        Street::create(['city_id' => 6, 'name' => 'Avenida Senador Souza Naves - Centro']);
        Street::create(['city_id' => 6, 'name' => 'Rua General Neto - Centro']);
        Street::create(['city_id' => 345, 'name' => 'Praça Desembargador Tomaz Salustino - Centro']);
        Street::create(['city_id' => 260, 'name' => 'Rua Tenente Ireneu Lacerda - Centro']);
        Street::create(['city_id' => 172, 'name' => 'Rua Dorcília Cândia de Jesus - Setor Central']);
        Street::create(['city_id' => 172, 'name' => 'Avenida Davi Alves Silva - Centro']);
        Street::create(['city_id' => 314, 'name' => 'Avenida Padre Joaquim Nonato - Centro']);
        Street::create(['city_id' => 448, 'name' => 'Rua José Bonifácio  - Centro']);
        Street::create(['city_id' => 48, 'name' => 'Rua Raimundo da Conceição Tabireza - Centro']);
        Street::create(['city_id' => 101, 'name' => 'Rua Maria Gomes de Aguiar - Centro']);
        Street::create(['city_id' => 449, 'name' => 'Praça Dom Bosco - Centro']);
        Street::create(['city_id' => 488, 'name' => 'Avenida CODESPAR 808 - Setor Central']);
        Street::create(['city_id' => 346, 'name' => 'Rua Otília Jácome  - Centro']);
        Street::create(['city_id' => 124, 'name' => 'Avenida Rio do Peixe - Setor Central']);
        Street::create(['city_id' => 316, 'name' => 'Praça Santa Teresinha 86 Térreo Térreo - Matias']);
        Street::create(['city_id' => 450, 'name' => 'Rua Maria Perpétua Piedade Gonçalves  - Centro']);
        Street::create(['city_id' => 451, 'name' => 'Rua Alfredo Lanzi - Centro']);
        Street::create(['city_id' => 126, 'name' => 'Rua Cinco - Setor Central']);
        Street::create(['city_id' => 483, 'name' => 'Avenida Valdenice Gomes da Siilva - Centro']);
        Street::create(['city_id' => 483, 'name' => 'Avenida Petronilio Menezes De Cotia - Tancredo Neves']);
        Street::create(['city_id' => 173, 'name' => 'Avenida Brasil - Centro']);
        Street::create(['city_id' => 452, 'name' => 'Praça Independência - Vila Romanópolis']);
        Street::create(['city_id' => 49, 'name' => 'Praça Pompílio Céo - Centro']);
        Street::create(['city_id' => 261, 'name' => 'Rua José Mariano Barbosa - Centro']);
        Street::create(['city_id' => 453, 'name' => 'Rua João Pereira Dias  - Centro']);
        Street::create(['city_id' => 454, 'name' => 'Alameda Gulla 373 - Centro']);
        Street::create(['city_id' => 361, 'name' => 'Avenida Borges de Medeiros - Centro']);
        Street::create(['city_id' => 174, 'name' => 'Rua Vereador José Andrade  - Centro']);
        Street::create(['city_id' => 175, 'name' => 'Rua 7 de Setembro - Centro']);
        Street::create(['city_id' => 127, 'name' => 'Rua João de Oliveira Gouveia  - Setor Central']);
        Street::create(['city_id' => 347, 'name' => 'Rua Manoel Salviano - Centro']);
        Street::create(['city_id' => 177, 'name' => 'Rua Santa Rita - Centro']);
        Street::create(['city_id' => 178, 'name' => 'Avenida 11 de Março  - Centro']);
        Street::create(['city_id' => 381, 'name' => 'Avenida Pedras Brancas - Centro']);
        Street::create(['city_id' => 102, 'name' => 'Rua São José - Centro']);
        Street::create(['city_id' => 179, 'name' => 'Rua Colaço Veras  - Centro']);
        Street::create(['city_id' => 181, 'name' => 'Rua do Comércio 1371-B - Centro']);
        Street::create(['city_id' => 362, 'name' => 'Avenida Santa Cruz - Centro']);
        Street::create(['city_id' => 294, 'name' => 'Rua José Gonçalves de Santana - Porta Florada']);
        Street::create(['city_id' => 363, 'name' => 'Avenida José Loureiro da Silva - Centro']);
        Street::create(['city_id' => 364, 'name' => 'Avenida Borges de Medeiros - Centro']);
        Street::create(['city_id' => 455, 'name' => 'Avenida Coronel Quito - Centro']);
        Street::create(['city_id' => 396, 'name' => 'Rua Francisco das Chagas Magalhães  - Centro']);
        Street::create(['city_id' => 182, 'name' => 'Rua Maria Livino - Centro']);
        Street::create(['city_id' => 333, 'name' => 'Rua Olívia Faria  - Centro']);
        Street::create(['city_id' => 16, 'name' => 'Rua Laurita Almeida Barbosa - Centro']);
        Street::create(['city_id' => 216, 'name' => 'Avenida Reynaldo Massi - Centro']);
        Street::create(['city_id' => 128, 'name' => 'Praça Daguiberto Caetano Pereira - Setor Central']);
        Street::create(['city_id' => 103, 'name' => 'Praça Hilda Garcia - Centro']);
        Street::create(['city_id' => 129, 'name' => 'Rua Joaquim G. Pádua  - Setor Central']);
        Street::create(['city_id' => 262, 'name' => 'Rua Adalberto Pereira de Lima - Centro']);
        Street::create(['city_id' => 184, 'name' => 'Rua 13 de Maio - Centro']);
        Street::create(['city_id' => 348, 'name' => 'Rua Santos Dumont - Centro']);
        Street::create(['city_id' => 349, 'name' => 'Rua Doutor Sílvio B. de Melo  - Centro']);
        Street::create(['city_id' => 17, 'name' => 'Rua Tancredo Neves - Agreste']);
        Street::create(['city_id' => 489, 'name' => 'Avenida Tertuliano Santos - Setor Central']);
        Street::create(['city_id' => 88, 'name' => 'Rua Major Idelfonso - Centro']);
        Street::create(['city_id' => 263, 'name' => 'Rua Presidente João Pessoa - Centro']);
        Street::create(['city_id' => 52, 'name' => 'Avenida Doutor Edilson Pontes - Centro']);
        Street::create(['city_id' => 18, 'name' => 'Avenida Coaracy Nunes - Central']);
        Street::create(['city_id' => 53, 'name' => 'Avenida Gabriel Dantas de Novaes - Centro']);
        Street::create(['city_id' => 19, 'name' => 'Rua Veiga Cabral - Mazagão']);
        Street::create(['city_id' => 317, 'name' => 'Rua Humaitá  - Centro']);
        Street::create(['city_id' => 89, 'name' => 'Rua José Sobreira da Cruz  - Centro']);
        Street::create(['city_id' => 130, 'name' => 'Avenida Rio Verde - Setor Central']);
        Street::create(['city_id' => 132, 'name' => 'Avenida Alipio Antônio de Paiva - Setor Central']);
        Street::create(['city_id' => 90, 'name' => 'Rua Coronel José Epifânio - Centro']);
        Street::create(['city_id' => 397, 'name' => 'Avenida Nossa Senhora de Fátima  - Centro']);
        Street::create(['city_id' => 217, 'name' => 'Praça Adolfo Alves Barreto - Centro']);
        Street::create(['city_id' => 217, 'name' => 'Rua Francisco Ferreira - Setor Central']);
        Street::create(['city_id' => 490, 'name' => 'Rua Doutor Raul Travassos - Centro']);
        Street::create(['city_id' => 490, 'name' => 'Praça da Bandeira - Setor Central']);
        Street::create(['city_id' => 218, 'name' => 'Avenida Iguatemi - Centro']);
        Street::create(['city_id' => 398, 'name' => 'Avenida Maurício Hambert - Centro']);
        Street::create(['city_id' => 219, 'name' => 'Rua Cassiano Leal Pael - Centro']);
        Street::create(['city_id' => 220, 'name' => 'Avenida Eurico Soares de Andrade - Centro']);
        Street::create(['city_id' => 137, 'name' => 'Rua Santos Dumont - Centro']);
        Street::create(['city_id' => 382, 'name' => 'Rua Rui Barbosa - Centro']);
        Street::create(['city_id' => 55, 'name' => 'Avenida Bernardino Rodrigues de Matos - Centro']);
        Street::create(['city_id' => 365, 'name' => 'Rua São Nicolau - Centro']);
        Street::create(['city_id' => 351, 'name' => 'Rua Antônio Viana Barbosa  - Centro']);
        Street::create(['city_id' => 244, 'name' => 'Avenida Treze de Maio - Centro']);
        Street::create(['city_id' => 456, 'name' => 'Rua Sete de Setembro - Centro']);
        Street::create(['city_id' => 56, 'name' => 'Rua Gildasio Souza - Centro']);
        Street::create(['city_id' => 56, 'name' => 'Avenida Quatorze de Dezembro - Centro']);
        Street::create(['city_id' => 335, 'name' => 'Avenida José Ruiz Bolea - Centro']);
        Street::create(['city_id' => 140, 'name' => 'Avenida Sargento Leontino - Setor Central']);
        Street::create(['city_id' => 457, 'name' => 'Avenida Adolfo Rodrigues - Centro']);
        Street::create(['city_id' => 458, 'name' => 'Rua Ozias Ávila de Menezes  - Centro']);
        Street::create(['city_id' => 57, 'name' => 'Praça São José - Centro']);
        Street::create(['city_id' => 336, 'name' => 'Rodovia Presidente Dutra - Prata']);
        Street::create(['city_id' => 142, 'name' => 'Avenida Independência  - Setor Central']);
        Street::create(['city_id' => 459, 'name' => 'Avenida Nosso Senhor do Bonfim 472 Box - Centro']);
        Street::create(['city_id' => 245, 'name' => 'Avenida Brasil 15 Quilômetro  - Centro']);
        Street::create(['city_id' => 58, 'name' => 'Praça do Comércio - Centro']);
        Street::create(['city_id' => 460, 'name' => 'Rua Pedro Pereira Dias - Centro']);
        Street::create(['city_id' => 383, 'name' => 'Avenida Deziderio Domingos Lopes - Centro']);
        Street::create(['city_id' => 461, 'name' => 'Rua Rio Branco - Centro']);
        Street::create(['city_id' => 491, 'name' => 'Rua Jeremias Pereira - Centro']);
        Street::create(['city_id' => 491, 'name' => 'Rua Presidente João Pessoa - Centro']);
        Street::create(['city_id' => 491, 'name' => 'Avenida Goiás  - Setor Central']);
        Street::create(['city_id' => 188, 'name' => 'Rua do Comércio - Centro']);
        Street::create(['city_id' => 32, 'name' => 'Rua 07 de Setembro - Centro']);
        Street::create(['city_id' => 492, 'name' => 'Rua 22 de Abril - Setor Central']);
        Street::create(['city_id' => 92, 'name' => 'Rua Manuel Peixoto - Centro']);
        Street::create(['city_id' => 318, 'name' => 'Avenida Valdir Leite - Centro']);
        Street::create(['city_id' => 318, 'name' => 'Avenida Santa Rita 826 Sala - Centro']);
        Street::create(['city_id' => 384, 'name' => 'Rua Carolino Machado - Centro']);
        Street::create(['city_id' => 384, 'name' => 'Avenida Ayrton Senna - Centro']);
        Street::create(['city_id' => 104, 'name' => 'Praça Jones dos Santos Neves - Centro']);
        Street::create(['city_id' => 414, 'name' => 'Praça João Stival - Setor Central']);
        Street::create(['city_id' => 414, 'name' => 'Rua Doutor Cesare Tibaldeschi 186 Sala - Centro']);
        Street::create(['city_id' => 61, 'name' => 'Avenida Oceânica - Centro']);
        Street::create(['city_id' => 462, 'name' => 'Rua Major João Batista Novais  - Centro']);
        Street::create(['city_id' => 493, 'name' => 'Avenida Primeiro de Maio - Setor Central']);
        Street::create(['city_id' => 33, 'name' => 'Avenida João Paulo  - Centro']);
        Street::create(['city_id' => 494, 'name' => 'Rua Doutor João de Abreu  - Setor Central']);
        Street::create(['city_id' => 34, 'name' => 'Avenida 16 de Fevereiro 122 Shopping Mte Álvaro Piso L1 Loja  - Centro']);
        Street::create(['city_id' => 146, 'name' => 'Avenida Joaquim Pacheco de Macedo - Setor Central']);
        Street::create(['city_id' => 147, 'name' => 'Avenida Perimetral - Núcleo Habitacional Novo Gama']);
        Street::create(['city_id' => 463, 'name' => 'Rua José Castorino de Abreu - Centro']);
        Street::create(['city_id' => 463, 'name' => 'Rua José Fabro  - Centro']);
        Street::create(['city_id' => 463, 'name' => 'Praça Doutor Euclydes Cardoso Castilho - Centro']);
        Street::create(['city_id' => 385, 'name' => 'Rua 25 de agosto - Centro']);
        Street::create(['city_id' => 221, 'name' => 'Avenida Marcos Freire - Centro']);
        Street::create(['city_id' => 264, 'name' => 'Rua Aleixo Francisco dos Santos - Centro']);
        Street::create(['city_id' => 93, 'name' => 'Rua Quinze de Novembro - Centro']);
        Street::create(['city_id' => 149, 'name' => 'Avenida Osvaldo Ferreira Sena - Setor Central']);
        Street::create(['city_id' => 247, 'name' => 'Rua Quinze de Novembro - Santa Luzia']);
        Street::create(['city_id' => 201, 'name' => 'Avenida Oscar Zaiden de Menezes - Centro']);
        Street::create(['city_id' => 63, 'name' => 'Praça Pedro Macário - Centro']);
        Street::create(['city_id' => 20, 'name' => 'Avenida Barão do Rio Branco  - Centro']);
        Street::create(['city_id' => 7, 'name' => 'Rua Prefeito Gilberto Cavalcante - Centro']);
        Street::create(['city_id' => 464, 'name' => 'Avenida Ismael - Centro']);
        Street::create(['city_id' => 465, 'name' => 'Avenida Vereador Osvaldo Kushida - Centro']);
        Street::create(['city_id' => 466, 'name' => 'Rua Hans Clotz - Centro']);
        Street::create(['city_id' => 467, 'name' => 'Rua João Maria Conrado 87 Sala  - Centro']);
        Street::create(['city_id' => 467, 'name' => 'Avenida Brasil - Centro']);
        Street::create(['city_id' => 151, 'name' => 'Avenida do Comércio  - Setor Central']);
        Street::create(['city_id' => 266, 'name' => 'Rua Rio de Janeiro - Centro']);
        Street::create(['city_id' => 152, 'name' => 'Avenida Irapuan Costa Júnior  - Setor Central']);
        Street::create(['city_id' => 417, 'name' => 'Rua John Kennedy 145 Sala 7 e - Centro']);
        Street::create(['city_id' => 267, 'name' => 'Rua Manoel Ribas - Centro']);
        Street::create(['city_id' => 321, 'name' => 'Rua José Salustiano da Silva  - Centro']);
        Street::create(['city_id' => 352, 'name' => 'Rua Ricardo Luiz Cavalcante - Centro']);
        Street::create(['city_id' => 353, 'name' => 'Praça Claudino Martins - Centro']);
        Street::create(['city_id' => 202, 'name' => 'Avenida Lions Internacional - Centro']);
        Street::create(['city_id' => 191, 'name' => 'Rua Celso Magalhães de Almeida  - Centro']);
        Street::create(['city_id' => 484, 'name' => 'Travessa da Ana da Fonseca - Centro']);
        Street::create(['city_id' => 8, 'name' => 'Rua Doutor Antonio Dorta - Centro']);
        Street::create(['city_id' => 22, 'name' => 'Travessa Lourenço de Araujo 552 - Centro']);
        Street::create(['city_id' => 386, 'name' => 'Avenida Pinheiro Machado - Centro']);
        Street::create(['city_id' => 268, 'name' => 'Rua Pedro Scheidt - Centro']);
        Street::create(['city_id' => 23, 'name' => 'Avenida São Pedro  - Centro']);
        Street::create(['city_id' => 468, 'name' => 'Rua Sete de Setembro - Centro']);
        Street::create(['city_id' => 66, 'name' => 'Avenida Sete de Setembro - Centro']);
        Street::create(['city_id' => 192, 'name' => 'Avenida Pedro Dareu - Centro']);
        Street::create(['city_id' => 295, 'name' => 'Praça Marechal Castelo Branco - Centro']);
        Street::create(['city_id' => 387, 'name' => 'Rua Jonas Antônio de Souza  - Centro']);
        Street::create(['city_id' => 203, 'name' => 'Rua Paranatinga - Centro']);
        Street::create(['city_id' => 269, 'name' => 'Avenida Coronel Rogério Borba - Centro']);
        Street::create(['city_id' => 204, 'name' => 'Avenida José Julio Lima  - Centro']);
        Street::create(['city_id' => 270, 'name' => 'Rua Pedro Siqueira - Centro']);
        Street::create(['city_id' => 323, 'name' => 'Rua Landri Sales - Centro']);
        Street::create(['city_id' => 271, 'name' => 'Rua Rio Amazonas - Centro']);
        Street::create(['city_id' => 105, 'name' => 'Rua Major Caetano - Centro']);
        Street::create(['city_id' => 35, 'name' => 'Rua Governador José Lindoso  - Centro']);
        Street::create(['city_id' => 154, 'name' => 'Rua Coronel Vaiano - Medeiros']);
        Street::create(['city_id' => 222, 'name' => 'Rua Barão do Rio Branco - Centro']);
        Street::create(['city_id' => 400, 'name' => 'Rua Pedro Daniel Silva - Centro']);
        Street::create(['city_id' => 272, 'name' => 'Avenida São Paulo  - Centro']);
        Street::create(['city_id' => 419, 'name' => 'Rua Lourenço Vivan  - Centro']);
        Street::create(['city_id' => 68, 'name' => 'Avenida da França - Comércio']);
        Street::create(['city_id' => 250, 'name' => 'Avenida Victor Engelhard - Centro']);
        Street::create(['city_id' => 273, 'name' => 'Avenida Getúlio Vargas  - Centro']);
        Street::create(['city_id' => 296, 'name' => 'Rua Padre Cícero - Centro']);
        Street::create(['city_id' => 69, 'name' => 'Rua Firmino Alves - Centro']);
        Street::create(['city_id' => 274, 'name' => 'Avenida Santos Dumont - Centro']);
        Street::create(['city_id' => 297, 'name' => 'Praça da Alegria - Centro']);
        Street::create(['city_id' => 70, 'name' => 'Praça Luís Viana Filho - Centro']);
        Street::create(['city_id' => 205, 'name' => 'Avenida dos Flávio Luiz  - Centro']);
        Street::create(['city_id' => 24, 'name' => 'Avenida Souza Mar - Comercial']);
        Street::create(['city_id' => 366, 'name' => 'Rua Doutor Gildásio A. de Oliveira - Prado']);
        Street::create(['city_id' => 251, 'name' => 'Avenida Francisco M. de Oliveira - Centro']);
        Street::create(['city_id' => 275, 'name' => 'Rua Dona Isabel - Centro']);
        Street::create(['city_id' => 485, 'name' => 'Rua João Bebe Agua - Centro']);
        Street::create(['city_id' => 420, 'name' => 'Avenida Lions - Centro']);
        Street::create(['city_id' => 325, 'name' => 'Rua São João Batista - Centro']);
        Street::create(['city_id' => 276, 'name' => 'Rua Corifeu de Azevedo Marques - Centro']);
        Street::create(['city_id' => 277, 'name' => 'Praça Santa Cruz - Centro']);
        Street::create(['city_id' => 278, 'name' => 'Praça José Maria Soares - Centro']);
        Street::create(['city_id' => 326, 'name' => 'Praça Prefeito Jurandir José Duarte - Centro']);
        Street::create(['city_id' => 367, 'name' => 'Rua do Comércio - Centro']);
        Street::create(['city_id' => 207, 'name' => 'Rua José Salmen Hanze  - Centro']);
        Street::create(['city_id' => 337, 'name' => 'Rua Professora Emília Esteves - Centro']);
        Street::create(['city_id' => 402, 'name' => 'Avenida Boa Vista - Centro']);
        Street::create(['city_id' => 421, 'name' => 'Avenida São Luiz  - Centro']);
        Street::create(['city_id' => 36, 'name' => 'Rua Getúlio Vargas  - Centro']);
        Street::create(['city_id' => 279, 'name' => 'Avenida Doutor Cícero de Moraes - Centro']);
        Street::create(['city_id' => 497, 'name' => 'Avenida JK 150 - Setor Central']);
        Street::create(['city_id' => 368, 'name' => 'Avenida Castelo Branco - Centro']);
        Street::create(['city_id' => 498, 'name' => 'Avenida Tocantins - Setor Central']);
        Street::create(['city_id' => 354, 'name' => 'Rua Euclides Lins de Albuquerque - Centro']);
        Street::create(['city_id' => 354, 'name' => 'Praça Barão do Rio Branco - Centro']);
        Street::create(['city_id' => 298, 'name' => 'Rua Dom Pedro II - Centro']);
        Street::create(['city_id' => 298, 'name' => 'Rua João de Araujo - Centro']);
        Street::create(['city_id' => 223, 'name' => 'Avenida João Selvirio de Souza  - Centro']);
        Street::create(['city_id' => 355, 'name' => 'Rua Santo Antônio - Centro']);
        Street::create(['city_id' => 25, 'name' => 'Quadra BC-04 156 - Vila Primária']);
        Street::create(['city_id' => 356, 'name' => 'Rua Joaquim Vicente de Melo - Centro']);
        Street::create(['city_id' => 338, 'name' => 'Rua Borges Alfredique - Centro']);
        Street::create(['city_id' => 157, 'name' => 'Rua Coronel Vicente Miguel - Setor Central']);
        Street::create(['city_id' => 499, 'name' => 'Avenida Sexta Avenida - Setor Central']);
        Street::create(['city_id' => 37, 'name' => 'Rua Coronel Garcia - Centro']);
        Street::create(['city_id' => 357, 'name' => 'Rua José Ferreira de Lima 51-A - Centro']);
        Street::create(['city_id' => 500, 'name' => 'Rua Leonino de Ramos Caiado - Setor Central']);
        Street::create(['city_id' => 26, 'name' => 'Rua Mãe Verônica  - Centro']);
        Street::create(['city_id' => 9, 'name' => 'Rua Jacinto Gerônimo - Centro']);
        Street::create(['city_id' => 299, 'name' => 'Avenida César Borges - Centro']);
        Street::create(['city_id' => 299, 'name' => 'Praça Coronel Jeremias Parente de Sá - Centro']);
        Street::create(['city_id' => 209, 'name' => 'Praça Treze de Maio - Centro']);
        Street::create(['city_id' => 422, 'name' => 'Rua Professor José Abatti - Centro']);
        Street::create(['city_id' => 195, 'name' => 'Rua da Salvação - Jerusalém']);
        Street::create(['city_id' => 158, 'name' => 'Avenida Goiânia  - Setor Central']);
        Street::create(['city_id' => 159, 'name' => 'Rua José Mário da Costa Rezende  - Setor Central']);
        Street::create(['city_id' => 423, 'name' => 'Avenida Doze de Maio - Centro']);
        Street::create(['city_id' => 423, 'name' => 'Rua Frei Gregório Dalmonte  - Centro']);
        Street::create(['city_id' => 282, 'name' => 'Rua Professor Cleto - Centro']);
        Street::create(['city_id' => 388, 'name' => 'Avenida Acir José Damasceno - Centro']);
        Street::create(['city_id' => 389, 'name' => 'Avenida Paraíso - Centro']);
        Street::create(['city_id' => 339, 'name' => 'Praça da República - Centro']);
        Street::create(['city_id' => 339, 'name' => 'Rua Bernardo Viana 52 Fundos - Centro']);
        Street::create(['city_id' => 327, 'name' => 'Rua Epaminondas Nogueira - Centro']);
        Street::create(['city_id' => 77, 'name' => 'Praça Petronílio Lopes - Centro']);
        Street::create(['city_id' => 469, 'name' => 'Rua Manoel Parada de Carvalho - Centro']);
        Street::create(['city_id' => 160, 'name' => 'Rua da BR-040 - Parque Rio Branco']);
        Street::create(['city_id' => 424, 'name' => 'Rua Mamante Danielli 77 Sala - Centro']);
        Street::create(['city_id' => 470, 'name' => 'Rua Geraldino de Oliveira - Centro']);
        Street::create(['city_id' => 106, 'name' => 'Rua Paulino Francisco Moreira - Centro']);
        Street::create(['city_id' => 426, 'name' => 'Avenida São Paulo  - Centro']);
        Street::create(['city_id' => 426, 'name' => 'Rua Sidiney Roman - Centro']);
        Street::create(['city_id' => 196, 'name' => 'Rua Doutor Nina Rodrigues - Centro']);
        Street::create(['city_id' => 471, 'name' => 'Rua Major Correa - Centro']);
        Street::create(['city_id' => 472, 'name' => 'Rua Mário Scarvance - Centro']);
        Street::create(['city_id' => 162, 'name' => 'Rua Joaquim P. Oliveira - Setor Central']);
        Street::create(['city_id' => 94, 'name' => 'Rua Modesto de Mendonça  - Centro']);
        Street::create(['city_id' => 340, 'name' => 'Rua Deputado Francelino Bastos França  - Centro']);
        Street::create(['city_id' => 358, 'name' => 'Rua 11 de Janeiro - Centro']);
        Street::create(['city_id' => 358, 'name' => 'Rua Deputado José Lúcio Ribeiro - Centro']);
        Street::create(['city_id' => 95, 'name' => 'Rua José Correia Sobrinho  - Centro']);
        Street::create(['city_id' => 78, 'name' => 'Praça Alfredo Navarro - Centro']);
        Street::create(['city_id' => 79, 'name' => 'Praça Edvaldo Valois - Centro']);
        Street::create(['city_id' => 329, 'name' => 'Avenida Castelo Branco - Centro-Sul']);
        Street::create(['city_id' => 80, 'name' => 'Rua Padre Alfredo Haasler - Centro']);
        Street::create(['city_id' => 473, 'name' => 'Avenida Fernão Dias Paes Leme - Centro']);
        Street::create(['city_id' => 341, 'name' => 'Rua Irmã Maria Agostinha  - Centro']);
        Street::create(['city_id' => 107, 'name' => 'Avenida Domingos Perim - Centro']);
        Street::create(['city_id' => 359, 'name' => 'Avenida Ministro Aluízio Alves - Centro']);
        Street::create(['city_id' => 283, 'name' => 'Avenida Anacleto Bueno de Camargo - Centro']);
        Street::create(['city_id' => 300, 'name' => 'Rua Antônio Bilui - Centro']);
        Street::create(['city_id' => 212, 'name' => 'Rua Chile - Centro']);
        Street::create(['city_id' => 474, 'name' => 'Rua da Rodagem - Centro']);
        Street::create(['city_id' => 474, 'name' => 'Rua Monsenhor Paiva - Centro']);
        Street::create(['city_id' => 474, 'name' => 'Rua Roberto Gruendling 231 Sala - Centro']);
        Street::create(['city_id' => 474, 'name' => 'Rua Doutora Cecília Rangel Janini  - Centro']);
        Street::create(['city_id' => 284, 'name' => 'Avenida Pedro Álvares Cabral - Centro']);
        Street::create(['city_id' => 285, 'name' => 'Avenida Getúlio Vargas  - Centro']);
        Street::create(['city_id' => 83, 'name' => 'Avenida Eujácio Simões - Centro']);
        Street::create(['city_id' => 225, 'name' => 'Praça Senhora do Patrocínio - Centro']);
        Street::create(['city_id' => 226, 'name' => 'Praça Vereador Fernando S. Melo - Centro']);
        Street::create(['city_id' => 228, 'name' => 'Rua Prefeito Wilson Damião - Centro']);
        Street::create(['city_id' => 303, 'name' => 'Praça Agamenon Magalhães - Centro']);
        Street::create(['city_id' => 229, 'name' => 'Rua Vereador Dumas Chalita - Centro']);
        Street::create(['city_id' => 197, 'name' => 'Rua Dois - Centro']);
        Street::create(['city_id' => 163, 'name' => 'Rua Felismino Viana 203 Sala - Setor Central']);
        Street::create(['city_id' => 304, 'name' => 'Rua Oliveira Estelita - Centro']);
        Street::create(['city_id' => 369, 'name' => 'Avenida Rio Branco - Centro']);
        Street::create(['city_id' => 224, 'name' => 'Rua Professor Bernardo Baur - Centro']);
        Street::create(['city_id' => 164, 'name' => 'Rua Tancredo Neves - Setor Central']);
        Street::create(['city_id' => 230, 'name' => 'Avenida Firmino Maia - Centro']);
        Street::create(['city_id' => 230, 'name' => 'Avenida Bueno Brandão  - Centro']);
        Street::create(['city_id' => 230, 'name' => 'Rua Ozeas Gomes Pinto - Centro']);
        Street::create(['city_id' => 96, 'name' => 'Rua Padre José Beviláqua - Centro']);
        Street::create(['city_id' => 370, 'name' => 'Avenida Vinte e Cinco de Julho - Centro']);
        Street::create(['city_id' => 427, 'name' => 'Rua Constâncio Krummel  - Centro']);
        Street::create(['city_id' => 428, 'name' => 'Rua Pedro Andreazza - Centro']);
        Street::create(['city_id' => 231, 'name' => 'Praça Dom Delfim - Centro']);
        Street::create(['city_id' => 213, 'name' => 'Rua Lino Bispo de Oliveira - Centro']);
        Street::create(['city_id' => 371, 'name' => 'Avenida das Flores - Centro']);
        Street::create(['city_id' => 373, 'name' => 'Rua General Flores da Cunha - Centro']);
        Street::create(['city_id' => 374, 'name' => 'Rua João Batista Becker  - Centro']);
        Street::create(['city_id' => 109, 'name' => 'Rua Vasco Fernandes Coutinho - Centro']);
        Street::create(['city_id' => 166, 'name' => 'Praça Santo Antônio - Setor Central']);
        Street::create(['city_id' => 214, 'name' => 'Avenida Brasil - Setor Norte']);
        Street::create(['city_id' => 110, 'name' => 'Rua Maria Dolores Tavares Bonela - Centro']);
        Street::create(['city_id' => 111, 'name' => 'Avenida Champagnat - Centro de Vila Velha']);
        Street::create(['city_id' => 390, 'name' => 'Avenida Marechal Rondon - Centro (S-01)']);
        Street::create(['city_id' => 475, 'name' => 'Rua Manoel Mateus - Capela']);
        Street::create(['city_id' => 476, 'name' => 'Rua São João - Centro']);
        Street::create(['city_id' => 232, 'name' => 'Avenida Brasil 120 Loja - Centro']);
        Street::create(['city_id' => 233, 'name' => 'Rua Crispim Gomes Pinto - Centro']);
        Street::create(['city_id' => 234, 'name' => 'Rua Marçal Barbalho  - Centro']);
        Street::create(['city_id' => 235, 'name' => 'Rua Prefeito Quim Júlio - Centro']);
        Street::create(['city_id' => 287, 'name' => 'Rua XV de Novembro - Centro']);
        Street::create(['city_id' => 236, 'name' => 'Rua Major Felicíssimo 256-A - Centro']);
        Street::create(['city_id' => 375, 'name' => 'Rua Anibal Negrini - Centro']);
        Street::create(['city_id' => 477, 'name' => 'Rua Herculano do Livramento - Centro']);
        Street::create(['city_id' => 376, 'name' => 'Rua Romualdo Tarasconi - Centro']);
        Street::create(['city_id' => 377, 'name' => 'Avenida Nove de Maio - Centro']);
        Street::create(['city_id' => 429, 'name' => 'Rua Sebastião Kammer  - Centro']);
        Street::create(['city_id' => 112, 'name' => 'Avenida Jerônimo Monteiro - Centro']);
        Street::create(['city_id' => 478, 'name' => 'Rua Doutor Nunes - Centro']);
        Street::create(['city_id' => 84, 'name' => 'Avenida Presidente Dutra - Centro']);
        Street::create(['city_id' => 378, 'name' => 'Rua dos Imigrantes - Centro']);
        Street::create(['city_id' => 305, 'name' => 'Avenida Henrique de Holanda - Matriz']);
        Street::create(['city_id' => 27, 'name' => 'Avenida Ayrton Senna - Centro']);
        Street::create(['city_id' => 256, 'name' => 'Avenida Manoel Félix de Farias - Centro']);
        Street::create(['city_id' => 288, 'name' => 'Avenida Brasil Argentina - Centro']);
        Street::create(['city_id' => 237, 'name' => 'Praça Bernardino Rocha - Centro']);
        Street::create(['city_id' => 342, 'name' => 'Rua Natal - Morro da Conquista']);
        Street::create(['city_id' => 479, 'name' => 'Avenida 31 de Março - Centro']);
        Street::create(['city_id' => 480, 'name' => 'Avenida Francisco Vilar Horta - Patrimônio Novo']);
    }
}
